### ISSUE TITLE
fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute 'keyserver'

### ISSUE THREAD

**Issue by gvillalta99** [gvillalta99/ansible-devenv#1]
## Playbook

```
---
- hosts: locals
  roles:
    - role: gvillalta99.devenv
      devenv:
        update: yes
```

## Output
>TASK: [gvillalta99.devenv | Install keys] ************************************* 
>fatal: [localhost] => One or more undefined variables: 'dict object' has no attribute 'keyserver'
>
>FATAL: all hosts have already failed -- aborting
